/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.SystemAdminWorkArea;

import Business.Customer.Customer;
import Business.CustomerOrder.BuyOrderItem;
import Business.EcoSystem;
import Business.Express.ExpressManager;
import Business.Network.Network;
import Business.Seller.Seller;
import java.awt.Font;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author 13522
 */
public class ChartJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChartJPanel
     */
   JPanel userProcessContainer;
    EcoSystem system;
    public ChartJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        jPanel1.add(NetworkBarChart());
        
    }
public ChartPanel NetworkBarChart(){
        //set data of chart
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for(Network net: system.getNetworkList()){
            int customerNum = 0;
            int buyOrderItemNum = 0;
            int sellerNum = 0;
           
            int expressNum = 0;
            for(Customer customer: net.getCustomerDirectory().getCustomersList()){
                customerNum++;
            }
            for(Seller seller: net.getSellerDirectory().getSellerList()){
                sellerNum++;

            }
            for(ExpressManager express: net.getExpressManagerDir().getExpressManagerList()){
                expressNum++;
            }
            
            dataset.addValue(customerNum, net.getName(), "Customer");
            dataset.addValue(sellerNum, net.getName(), "Seller");
            dataset.addValue(expressNum, net.getName(), "Express");
        }
        JFreeChart chart = ChartFactory.createBarChart3D(
       		                 "Number of three roles in Countries",
                            "Role", 
                            "Quantity", 
                            dataset, 
                            PlotOrientation.VERTICAL, 
                            true,           
                            false,          
                            false           
                            );
        
        
         CategoryPlot plot=chart.getCategoryPlot();
         CategoryAxis domainAxis=plot.getDomainAxis();         
         domainAxis.setLabelFont(new Font("黑体",Font.BOLD,16));        
         domainAxis.setTickLabelFont(new Font("宋体",Font.BOLD,14));  
         ValueAxis rangeAxis=plot.getRangeAxis();//获取柱状
         rangeAxis.setLabelFont(new Font("黑体",Font.BOLD,17));
         chart.getLegend().setItemFont(new Font("黑体", Font.BOLD, 17));
         chart.getTitle().setFont(new Font("宋体",Font.BOLD,22));
          
          
          
        ChartPanel frame1=new ChartPanel(chart,true);
        frame1.setBounds(1, 1, 400, 300);
        return frame1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(250, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(263, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
