/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Express.ExpressManager;
import Business.Feedback.Feedback;
import Business.Network.Network;
import Business.Role.ExpressManagerRole;
import Business.Role.FeedbackRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 13522
 */
public class ManageFeedbackJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagerFeedbackJPanle
     */
    private JPanel container;
    private EcoSystem system;
    private Network network;
    private UserAccount useraccount;
    public ManageFeedbackJPanel(JPanel userProcessContainer, EcoSystem ecosystem,Network network, UserAccount useraccount ) {
        initComponents();
        this.container = userProcessContainer;
        this.system = ecosystem;
        this.network=network;
        this.useraccount = useraccount;
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFeedbackManager = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnModify = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        lbllocation = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtManagerName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Location");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, -1, -1));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 147, -1));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, -1, -1));

        tblFeedbackManager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "AccountName", "Phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFeedbackManager);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 493, 112));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Choose a row then press Modify so that you can change the profile");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        btnModify.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModify.setText("Modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        add(btnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, -1, -1));

        btnCreate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, -1, -1));

        lbllocation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(lbllocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 115, 18));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Feedback Manager List:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Password");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, -1, 22));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("New Feedback Manager:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, 33));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Feedback Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("phone");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, -1, 22));

        txtManagerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManagerNameActionPerformed(evt);
            }
        });
        add(txtManagerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, 147, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("User Name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, -1, -1));
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 147, -1));
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 147, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 33, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/EBack.jpg"))); // NOI18N
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 630));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblFeedbackManager.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        Feedback em = (Feedback)tblFeedbackManager.getValueAt(selectedRow, 0);

        if(system.getUserAccountDirectory().checkIfUsernameIsUnique(txtUserName.getText())){}
        else{
            JOptionPane.showMessageDialog(null, "This username has existed!", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }

        //check format of username and password

        em.setName( txtManagerName.getText());
        em.setPhone(txtPhone.getText());
        em.getUseraccount().setPassword(txtPassword.getText());
        em.getUseraccount().setUsername(txtUserName.getText()) ;

        txtManagerName.setText("");
        txtUserName.setText("");
        txtPassword.setText("");
       
        txtPhone.setText("");

        btnSave.setEnabled(false);
        btnModify.setEnabled(true);

        refreshTable();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblFeedbackManager.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }

        Feedback em = (Feedback)tblFeedbackManager.getValueAt(selectedRow, 0);
        network.getFeedbackDir().getFeedbacklist().remove(em);
        UserAccount ua=new UserAccount();
        ua=em.getUseraccount();
        system.getUserAccountDirectory().getUserAccountList().remove(ua);

        JOptionPane.showMessageDialog(null, "Delete the ExpressManager successfully!");
        refreshTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed

        int selectedRow = tblFeedbackManager.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        Feedback em = ( Feedback)tblFeedbackManager.getValueAt(selectedRow, 0);
        txtManagerName.setText(em.getName());
        txtUserName.setText(em.getUseraccount().getUsername());
        txtPassword.setText(em.getUseraccount().getPassword());
        txtPhone.setText(em.getPhone());
        
        btnSave.setEnabled(true);
        btnModify.setEnabled(false);
        btnCreate.setEnabled(false);
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        if(txtManagerName.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Invalid Name!");
        }else if(txtUserName.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Invalid UserName!");
        }else if(txtPassword.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Invalid Password!");
        }else if(txtPhone.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Invalid Password!");
        }else{
        String userName = txtUserName.getText();
        String password = txtPassword.getText();
        String managerName = txtManagerName.getText();
        
        String phone = txtPhone.getText();
        if(system.getUserAccountDirectory().checkIfUsernameIsUnique(userName)){}
        else{
            JOptionPane.showMessageDialog(null, "This username has existed!", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }

        //        Organization organization = (Organization) cmbOrganization.getSelectedItem();
        //        Employee employee = (Employee) cmbEmployee.getSelectedItem();
        //        Role role = (Role) cmbRoles.getSelectedItem();
        Feedback em = new Feedback();
        UserAccount useraccount=new UserAccount();
        Employee e1 = system.getEmployeeDirectory().createEmployee(managerName);
        useraccount=system.getUserAccountDirectory().createUserAccount(userName, password, e1, new FeedbackRole());
        em.setName(managerName);
        em.setPhone(phone);
        
        em.setUseraccount(useraccount);
       
        network.getFeedbackDir().getFeedbacklist().add(em);
        network.getUserAccountDirectory().getUserAccountList().add(useraccount);
        JOptionPane.showMessageDialog(null, "User Account added successfully.");
        txtUserName.setText("");
        txtPassword.setText("");
        txtManagerName.setText("");
        txtPhone.setText("");
        refreshTable();
    }//GEN-LAST:event_btnCreateActionPerformed
    }
    private void txtManagerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManagerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManagerNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbllocation;
    private javax.swing.JTable tblFeedbackManager;
    private javax.swing.JTextField txtManagerName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tblFeedbackManager.getModel();
        model.setRowCount(0);

        for(Feedback em: network.getFeedbackDir().getFeedbacklist()){
            Object row[] = new Object[3];
             row[0] = em;
           row[1] = em.getUseraccount().getUsername();
           row[2] = em.getPhone();

            
            model.addRow(row);
       
    }
        lbllocation.setText(network.getName());
    }


}
