/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.FeedbackRole;

import Business.CustomerOrder.BuyOrderItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author 13522
 */
public class ProcessingOrder1JPanel extends javax.swing.JPanel {

       JPanel userProcessContainer;
     BuyOrderItem buyOrderItem;
      String chatRecord;
    /**
     * Creates new form ProcessingOrderJPanel
     */
    

   public ProcessingOrder1JPanel(JPanel userProcessContainer, BuyOrderItem buyOrderItem) {
         initComponents();
         this.userProcessContainer = userProcessContainer;
         this.buyOrderItem = buyOrderItem;
         
         refreshTable();
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtChatRecord = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtChatBox = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtChatRecord.setColumns(20);
        txtChatRecord.setLineWrap(true);
        txtChatRecord.setRows(5);
        txtChatRecord.setEnabled(false);
        jScrollPane1.setViewportView(txtChatRecord);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 350, 250));

        txtChatBox.setColumns(20);
        txtChatBox.setRows(5);
        jScrollPane2.setViewportView(txtChatBox);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 280, 250));

        jButton1.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jButton1.setText("Accept Refund");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 133, -1));

        jButton2.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jButton2.setText("Refuse Refund");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 141, -1));

        jButton3.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jButton3.setText("Send");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 81, -1));

        jLabel1.setFont(new java.awt.Font("宋体", 3, 36)); // NOI18N
        jLabel1.setText("      Processing Order");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 590, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/EBack.jpg"))); // NOI18N
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 630));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       buyOrderItem.getEvaluate().setRefund(true);
        JOptionPane.showMessageDialog(null, "Set Refund successfully!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         buyOrderItem.getEvaluate().setRefund(false);
        JOptionPane.showMessageDialog(null, "Refused Refund");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String word = txtChatBox.getText();

        String message =  " Customer service: " +" : " + word  + "\r\n";
        buyOrderItem.getFeedbackends().add(message);
        txtChatBox.setText("");

        refreshTable();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtChatBox;
    private javax.swing.JTextArea txtChatRecord;
    // End of variables declaration//GEN-END:variables
 private void refreshTable() {
        chatRecord = "";
        for(int i=0;i<buyOrderItem.getFeedbackends().size();i++){
             chatRecord=chatRecord +buyOrderItem.getFeedbackends().get(i)+"\r\n";
        }
        
             txtChatRecord.setText(chatRecord);
    }
}
