/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.CustomerRole;

import Business.CustomerOrder.BuyOrderItem;
import Business.EcoSystem;
import Business.Item.Item;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkQueue;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author 13522
 */
public class EpaymentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EpaymentJPanel
     */
   private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount useraccount;
    private Network net;
     ArrayList<Item> itemList = new ArrayList<Item>();
    ArrayList<BuyOrderItem> cart = new ArrayList<BuyOrderItem>();
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public EpaymentJPanel(JPanel userProcessContainer,Network net,EcoSystem system, UserAccount useraccount) {
        initComponents();
//        
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.net= net;
        this.useraccount = useraccount;
//        lblCustomerName.setText(((u.getEmployee() != null) ? u.getEmployee().getName() : u.getUsername()) + "!");
//        //valueLabel.setText(enterprise.getName());
//        wq.getRequestList();
        
           
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        loginJLogin = new javax.swing.JButton();
        loginJManage = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(51, 51, 51));
        enterpriseLabel.setText("Congrats to our new system, we send every customer a free 100 dollar");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 890, 60));

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 140, 27));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 140, 27));

        jLabel1.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel1.setText("E-password:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel2.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel2.setText("E-username:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        enterpriseLabel1.setText("Welcome!OUR E-Pay System");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 580, 30));

        jLabel3.setText("(default:test)");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        jLabel4.setText("(default:test)");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        jLabel5.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel5.setText("We sincerly recommend you to change your username and password");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        loginJLogin.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        loginJLogin.setText("Login");
        loginJLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJLoginActionPerformed(evt);
            }
        });
        add(loginJLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 100, -1));

        loginJManage.setText("Manage your E-payment");
        loginJManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJManageActionPerformed(evt);
            }
        });
        add(loginJManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 180, -1));

        btnBack.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 24, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/B.jpg"))); // NOI18N
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1020, 640));
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void loginJLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJLoginActionPerformed
        if(txtUsername.getText().equals(useraccount.getEpaccount().getUsername())&&txtPassword.getText().equals(useraccount.getEpaccount().getPassword())){
          CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add(new CustomerAreaJPanel(userProcessContainer,system,net,useraccount));
        layout.next(userProcessContainer);
    }else{
         JOptionPane.showMessageDialog(null, "Wrong username or account!");
            return;
        }
        
        
    }//GEN-LAST:event_loginJLoginActionPerformed

    private void loginJManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJManageActionPerformed
        // TODO add your handling code here:
         CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add(new EpayManageJPanel(userProcessContainer,net,system,useraccount));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_loginJManageActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton loginJLogin;
    private javax.swing.JButton loginJManage;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
