/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.CustomerRole;

import Business.CustomerOrder.BuyOrderItem;
import Business.EcoSystem;
import Business.Item.Item;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author 13522
 */
public class EpayManageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EpayManageJPanel
     */
   private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount useraccount;
    private Network net;
   
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public EpayManageJPanel(JPanel userProcessContainer,Network net,EcoSystem system, UserAccount useraccount) {
        initComponents();
//        
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.net= net;
        this.useraccount = useraccount;
//        lblCustomerName.setText(((u.getEmployee() != null) ? u.getEmployee().getName() : u.getUsername()) + "!");
//        //valueLabel.setText(enterprise.getName());
//        wq.getRequestList();
        
          refreshtable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtMoney = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnChange = new javax.swing.JButton();
        btnCharge = new javax.swing.JButton();
        lblmoney = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblppassword = new javax.swing.JLabel();
        lblpusername = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 102, 140, 27));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 140, 27));

        txtMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMoneyActionPerformed(evt);
            }
        });
        add(txtMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 140, 27));

        jLabel1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel1.setText("Username");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 106, -1, 20));

        jLabel2.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel2.setText("Password");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, 20));

        jLabel3.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel3.setText("Money Left:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        btnChange.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        btnChange.setText("Change profile");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });
        add(btnChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        btnCharge.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        btnCharge.setText("Charge");
        btnCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChargeActionPerformed(evt);
            }
        });
        add(btnCharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, -1, -1));

        lblmoney.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        add(lblmoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 126, 18));

        jLabel4.setFont(new java.awt.Font("宋体", 3, 18)); // NOI18N
        jLabel4.setText("Previous Username:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 66, -1, -1));

        jLabel5.setFont(new java.awt.Font("宋体", 3, 18)); // NOI18N
        jLabel5.setText("Previous Password:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 161, -1, -1));

        lblppassword.setFont(new java.awt.Font("宋体", 3, 18)); // NOI18N
        add(lblppassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 170, 20));

        lblpusername.setFont(new java.awt.Font("宋体", 3, 18)); // NOI18N
        add(lblpusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 160, 20));

        jLabel6.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel6.setText("Charge Money:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        btnBack.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 23, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/B.jpg"))); // NOI18N
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 630));
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMoneyActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
       useraccount.getEpaccount().setUsername(txtUsername.getText());
       useraccount.getEpaccount().setPassword(txtPassword.getText());
         JOptionPane.showMessageDialog(null, "All set");
         refreshtable();
           
      
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChargeActionPerformed
        // TODO add your handling code here:
        useraccount.getEpaccount().setMoney(useraccount.getEpaccount().getMoney()+Integer.parseInt(txtMoney.getText()));
        JOptionPane.showMessageDialog(null, "All set");
        refreshtable();
    }//GEN-LAST:event_btnChargeActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnCharge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblmoney;
    private javax.swing.JLabel lblppassword;
    private javax.swing.JLabel lblpusername;
    private javax.swing.JTextField txtMoney;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
public void refreshtable(){
lblpusername.setText( useraccount.getEpaccount().getUsername());
lblppassword.setText( useraccount.getEpaccount().getPassword());
lblmoney.setText( String.valueOf(useraccount.getEpaccount().getMoney()));
}
}
