/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkQueue;

import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class RequestLabTestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount u;
    private WorkQueue wq;
    /**
     * Creates new form RequestLabTestJPanel
     */
    public RequestLabTestJPanel(JPanel userProcessContainer,EcoSystem system, UserAccount account,WorkQueue wq) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.u = account;
        this.wq = wq;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        cmbDishID = new javax.swing.JComboBox<>();
        lblDishSet = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTestJButton.setText("Request Order");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        cmbDishID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose--", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cmbDishID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDishIDActionPerformed(evt);
            }
        });
        add(cmbDishID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 100, -1));

        lblDishSet.setText("Dish set");
        add(lblDishSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed

        WorkRequest request = new WorkRequest();
        request.setCustomerName((u.getEmployee() != null) ? u.getEmployee().getName() : u.getUsername());
        request.setSender(u);
        request.setStatus("Ordered");
        request.setOrder(cmbDishID.getSelectedItem().toString());
//        system.getWq().getOrderRequestList().add(request);
        wq.getRequestList().add(request);
      
        JOptionPane.showMessageDialog(null, "Order sent!");

        
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerAreaJPanel dwjp = (CustomerAreaJPanel) component;
//        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void cmbDishIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDishIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDishIDActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox<String> cmbDishID;
    private javax.swing.JLabel lblDishSet;
    private javax.swing.JButton requestTestJButton;
    // End of variables declaration//GEN-END:variables
}
