/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;


import Business.CustomerOrder.BuyOrderItem;
import Business.CustomerOrder.Evaluate;
import Business.Item.Comment;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author TT1
 */
public class WriteCommentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WriteCommentJPanel
     */
    JPanel userProcessContainer;
    BuyOrderItem item;
    UserAccount account;
    public WriteCommentJPanel(JPanel userProcessContainer,BuyOrderItem item, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.item = item;
        this.account = account;
        if(item.getEvaluate() != null&&item.getEvaluate().getWord()!=null){
            txtComment.setText(item.getEvaluate().getWord());
            txtComment.setEnabled(false);
            jSpinner1.setEnabled(false);
            btnCommit.setEnabled(false);
            jLabel2.setText(jLabel2.getText() + String.valueOf(item.getEvaluate().getScore()));
        }
        
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComment = new javax.swing.JTextArea();
        btnCommit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 1, 48)); // NOI18N
        jLabel1.setText("Comment");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 230, -1));

        txtComment.setColumns(20);
        txtComment.setRows(5);
        jScrollPane1.setViewportView(txtComment);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 513, -1));

        btnCommit.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        btnCommit.setText("comment");
        btnCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommitActionPerformed(evt);
            }
        });
        add(btnCommit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 100, -1));

        btnBack.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        btnBack.setText("< back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 56, -1));

        jLabel2.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel2.setText("score:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("0~10 ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, -1));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 13, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/B.jpg"))); // NOI18N
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 630));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommitActionPerformed
        // TODO add your handling code here:
        String word = txtComment.getText();
        int score = (Integer)jSpinner1.getValue();
        String buyerName = account.getUsername();
        Date date = new Date();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm");
        String datetime = format.format(date);
        if(score <0  || score >10){
            JOptionPane.showMessageDialog(null, "Quantity cannot be less than 0 or more than 10!", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(word.length()<=0){
            JOptionPane.showMessageDialog(null, "Comment could not be empty!", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Evaluate e=new Evaluate();
        e.setScore(score);
        e.setWord(word);
        e.setBuyer(buyerName);
        e.setDate(datetime);
        item.setEvaluate(e);
        Comment c = new Comment();
        c.setScore(score);
        c.setWord(word);
        c.setBuyer(buyerName);
        c.setDate(datetime);
        item.getItem().getComments().getCommentList().add(c);
        JOptionPane.showMessageDialog(null, "Comment successfully!");
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnCommitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCommit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea txtComment;
    // End of variables declaration//GEN-END:variables
}
